~ reorder and have set -e act on everything

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -87,13 +87,13 @@ matrix:
   - name: Clang-7 libc++
 
 before_install:
-- mkdir -p ~/tools
 - |
+  set -e # stop Bash execution on error
+  mkdir -p ~/tools
   eval "CC=${C_compiler:-$CC} && CXX=${CXX_compiler:-$CXX}"
 - |
   # Install Ninja-build
   (
-    set -e
     os=${TRAVIS_OS_NAME}
     file_name="ninja-${os}.zip"
     NINJA_URL="https://github.com/ninja-build/ninja/releases/download/${NINJA_VER}/${file_name}"
@@ -111,7 +111,6 @@ before_install:
   export PATH=$PATH:$HOME/tools/ninja/
 - |
   { # Install vcpkg
-    set -e
     if [[ -x ./vcpkg/vcpkg ]]; then
       cd ~/tools/vcpkg
       git pull --quiet
